stl:
	openscad-nightly -Dmode=0 -o tray.stl case.scad
	openscad-nightly -Dmode=1 -o cap1.stl case.scad
	openscad-nightly -Dmode=2 -o cap2.stl case.scad
	openscad-nightly -Dmode=3 -o cap_display.stl case.scad
	openscad-nightly -Dmode=4 -o cable_clip.stl case.scad
	openscad-nightly -Dmode=5 -o button_cap.stl case.scad
	openscad-nightly -o all.stl case.scad
